#
# Copyright (C) 2008-2015 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for syncy
LUCI_DEPENDS:=+python +python-curl +libcurl +libc +kmod-nls-utf8 +libopenssl

PKG_NAME:=luci-app-syncy
PKG_VERSION:=2.1.0
PKG_RELEASE:=0
PKG_LICENSE:=Apache-2.0
PKGARCH:=all

PKG_MAINTAINER:=wwbhl <8489216@qq.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

